--------------------------------------------------------
--  File created - Friday-March-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BRANCH" OF "SYSTEM"."BRANCH_TYPE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE "PHONE" STORE AS "BRANCH_PHONE_NESTED_TABLE"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
REM INSERTING into SYSTEM.BRANCH
SET DEFINE OFF;
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('colinton st.','Edinbutgh','EH11 5DT','901',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '00712345678')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Market st.','Edinburgh','EH1 5AB','902',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '01311235560')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Bridge st.','Glasglow','G18 1QQ','903',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '01413214556')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Chao Yang st.','London','E11 W1','904',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07702346542')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Queen st.','Edinburgh','EH6 5EE','905',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07756734561')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('RanTun st..','Edinburgh','EH4 5NE','906',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07734789541')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Marry st.','Edinburgh','EH1 4QH','907',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07765781234')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Ford st.','Edinburgh','EH8 2SE','908',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07798754671')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Horry st.','Edinburgh','EH12 2ER','909',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07712365438')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Royal Mill','Edinburgh','EH1 3AA','910',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '01315786541')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('King st.','Edinburgh','EH3 5AR','911',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '013198745612')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Qinling St.','Zhengzhou','450001','912',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '08618532109175')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Futian st.','Glasglow','450002','913',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '00861324243123')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Wenhua st.','Beijing','400000','914',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '00861234567')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Tianan st.','Edinburgh','EH1 1RR','915',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07741234281')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Yahoo st.','Oxford','11ER 3BT','917',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '01312314231')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Tianmao st.','Cambridge','CA1 AA3','918',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '01316547345')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Taobao','Striling','ST1 ER3','919',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '07341235781')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('MeiTuan st.','Dumdee','3AD 4SE','920',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '01234124365')));
Insert into SYSTEM.BRANCH (STREET,CITY,POSTCODE,BRANCH_ID,PHONE) values ('Jingdong st.','Stirling','E12 R12','921',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('branch', '03123198173')));
--------------------------------------------------------
--  DDL for Index BRANCH_ID_CONSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BRANCH_ID_CONSTR" ON "SYSTEM"."BRANCH" ("BRANCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007021
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007021" ON "SYSTEM"."BRANCH" ("SYS_NC0000700008$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007022
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007022" ON "SYSTEM"."BRANCH" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BRANCH
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BRANCH" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BRANCH" ADD UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BRANCH" ADD CONSTRAINT "BRANCH_ID_CONSTR" PRIMARY KEY ("BRANCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BRANCH" ADD CONSTRAINT "POSTCODE_CONST" CHECK (postcode IS NOT NULL) ENABLE;
  ALTER TABLE "SYSTEM"."BRANCH" ADD CONSTRAINT "STREET_CONST" CHECK (street IS NOT NULL) ENABLE;
  ALTER TABLE "SYSTEM"."BRANCH" ADD CONSTRAINT "PHONE_CONST" CHECK (phone IS NOT NULL) ENABLE;
  ALTER TABLE "SYSTEM"."BRANCH" ADD CONSTRAINT "CITY_CONST" CHECK (city IS NOT NULL) ENABLE;
