--------------------------------------------------------
--  File created - Friday-March-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER" OF "SYSTEM"."CUSTOMER_TYPE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 NESTED TABLE TREAT("ADDRESS" AS "BRANCH_TYPE")."PHONE" STORE AS "SYSNTHqUJwb3vRT+6l2aYhSEjtA=="
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE
 NESTED TABLE "PHONE" STORE AS "CUST_PHONE_NESTED_TABLE"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) RETURN AS VALUE;
REM INSERTING into SYSTEM.CUSTOMER
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Jack', 'Smith'),SYSTEM.ADDRESS_TYPE('Adam', 'Edinburgh', 'EH28XN'),'N1003',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01311112223'), SYSTEM.PHONE_NESTED('Mobile', '0781209890'), SYSTEM.PHONE_NESTED('Home', NULL)),'1002');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'Anna', 'Smith'),SYSTEM.ADDRESS_TYPE('Adam', 'Edinburgh', 'EH16EA'),'N1010',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01314425567'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1003');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Liam', 'Bain'),SYSTEM.ADDRESS_TYPE('NEW', 'Edinburgh', 'EH28XN'),'N1034',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01314425567'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1098');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Oliver', 'RAN'),SYSTEM.ADDRESS_TYPE('ParkheadAvenue', 'Edinburgh', 'EH114SE'),'N1201',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013145123908'), SYSTEM.PHONE_NESTED('Mobile', '07702840687'), SYSTEM.PHONE_NESTED('Home', NULL)),'1088');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Mark', 'Slack'),SYSTEM.ADDRESS_TYPE('Old', 'Edinburgh', 'EH94BB'),'N1120',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013145123908'), SYSTEM.PHONE_NESTED('Mobile', '07702840687'), SYSTEM.PHONE_NESTED('Home', NULL)),'1004');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'WEIGUANG', 'RAN'),SYSTEM.ADDRESS_TYPE('ParkheadAvenue', 'Edinburgh', 'EH114SE'),'N1002',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '07702840687'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1005');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'July', 'William'),SYSTEM.ADDRESS_TYPE('Old', 'Glasglow', 'GG14EE'),'N1004',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01312341241'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1006');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Peter', 'Bill'),SYSTEM.ADDRESS_TYPE('York', 'Edinburgh', 'EH43AB'),'N1005',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01314512313'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', '07704567123')),'1007');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Bush', 'Simon'),SYSTEM.ADDRESS_TYPE('Shenzhen', 'London', '11QE'),'N1007',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01314512313'), SYSTEM.PHONE_NESTED('Mobile', '0790342153212'), SYSTEM.PHONE_NESTED('Home', '07700987651')),'1008');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Yifu', 'Lai'),SYSTEM.ADDRESS_TYPE('Fountainpark', 'Edinburgh', 'EH11 5ER'),'N1008',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013123412345'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1009');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Kai', 'Fan'),SYSTEM.ADDRESS_TYPE('Fountainpark', 'Edinburgh', 'EH115ER'),'N1012',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013109812312'), SYSTEM.PHONE_NESTED('Mobile', '079051234091'), SYSTEM.PHONE_NESTED('Home', NULL)),'1010');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Yue', 'Zhao'),SYSTEM.ADDRESS_TYPE('Fountainpark', 'Edinburgh', 'EH115ER'),'N1013',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01310981243'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1011');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'June', 'Lucy'),SYSTEM.ADDRESS_TYPE('Old', 'Edinburgh', 'EH11BR'),'N1088',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01310981243'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1012');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'April', 'Marry'),SYSTEM.ADDRESS_TYPE('King', 'Edinburgh', 'EH35ER'),'N1078',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013187564123'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', '0131239418571')),'1013');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'Millie', 'Canny'),SYSTEM.ADDRESS_TYPE('Fred', 'Edinburgh', 'EH125DD'),'N1079',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013189172451'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', NULL)),'1014');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'May', 'Bery'),SYSTEM.ADDRESS_TYPE('Mill', 'Edinburgh', 'EH73TT'),'N1080',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013104123981'), SYSTEM.PHONE_NESTED('Mobile', '01312398173'), SYSTEM.PHONE_NESTED('Home', NULL)),'1015');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'Lily', 'Francesca'),SYSTEM.ADDRESS_TYPE('Fountainpark', 'Edinburgh', 'EH115ER'),'N1081',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013131287102'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', '0131982129312')),'1016');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Niuniu', 'Bee'),SYSTEM.ADDRESS_TYPE('Queen', 'York', 'EE2S3'),'N1082',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01376212982'), SYSTEM.PHONE_NESTED('Mobile', '077123912831'), SYSTEM.PHONE_NESTED('Home', '08812309182')),'1017');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Frank', 'David'),SYSTEM.ADDRESS_TYPE('Calvin', 'Glasglow', 'GG1TR2'),'N1083',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '01318712312'), SYSTEM.PHONE_NESTED('Mobile', NULL), SYSTEM.PHONE_NESTED('Home', '077012918212')),'1018');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mr', 'Neil', 'Fed'),SYSTEM.ADDRESS_TYPE('Zhengzhou', 'Henan', '4500001'),'N1084',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '00881351238123'), SYSTEM.PHONE_NESTED('Mobile', '008812371234141'), SYSTEM.PHONE_NESTED('Home', '0701287126412')),'1019');
Insert into SYSTEM.CUSTOMER (NAME,ADDRESS,NI_NUM,PHONE,CUST_ID) values (SYSTEM.NAME_TYPE('Mrs', 'Timi', 'Cram'),SYSTEM.ADDRESS_TYPE('Ticket', 'Edinburgh', 'EH55EE'),'N1085',SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED('Mobile', '013109128231'), SYSTEM.PHONE_NESTED('Mobile', '070123129812'), SYSTEM.PHONE_NESTED('Home', '0128231001244')),'1020');
--------------------------------------------------------
--  DDL for Index CUST_ID_CONST
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CUST_ID_CONST" ON "SYSTEM"."CUSTOMER" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007026
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007026" ON "SYSTEM"."CUSTOMER" ("SYS_NC0001600017$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007027
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007027" ON "SYSTEM"."CUSTOMER" ("SYS_NC0001300014$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007028
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007028" ON "SYSTEM"."CUSTOMER" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NINUM_CONSTR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NINUM_CONSTR" ON "SYSTEM"."CUSTOMER" ("NI_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER" ADD CONSTRAINT "NINUM_CONSTR" UNIQUE ("NI_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" ADD UNIQUE (TREAT("ADDRESS" AS "BRANCH_TYPE")."PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" ADD UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" ADD CONSTRAINT "CUST_ID_CONST" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" ADD CONSTRAINT "ADDRESS_CITY_CONST" CHECK (address.city IS NOT NULL) ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER" ADD CONSTRAINT "NAME_CONST" CHECK (name IS NOT NULL) ENABLE;
