--------------------------------------------------------
--  File created - Friday-March-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ACCOUNT" OF "SYSTEM"."ACCOUNT_TYPE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ACCOUNT
SET DEFINE OFF;
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1001,'current',821,'SYSTEM.BRANCH_TYPE(''colinton st.'', ''Edinbutgh'', ''EH11 5DT'', ''901'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''00712345678'')))','0.005',800,to_date('01-MAY-15','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1010,'saving',3122,'SYSTEM.BRANCH_TYPE(''colinton st.'', ''Edinbutgh'', ''EH11 5DT'', ''901'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''00712345678'')))','.02',null,to_date('01-MAY-15','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (8002,'current',821,'SYSTEM.BRANCH_TYPE(''Ford st.'', ''Edinburgh'', ''EH8 2SE'', ''908'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07798754671'')))','0.005',100,to_date('01-MAY-10','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1234,'current',1000,'SYSTEM.BRANCH_TYPE(''colinton st.'', ''Edinbutgh'', ''EH11 5DT'', ''901'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''00712345678'')))','0.023',600,to_date('14-JUN-97','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1101,'saving',9877,'SYSTEM.BRANCH_TYPE(''Wenhua st.'', ''Beijing'', ''400000'', ''914'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''00861234567'')))','0.023',600,to_date('14-JUN-97','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1102,'saving',1235,'SYSTEM.BRANCH_TYPE(''Horry st.'', ''Edinburgh'', ''EH12 2ER'', ''909'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07712365438'')))','0.01',10000,to_date('21-FEB-00','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1103,'saving',123,'SYSTEM.BRANCH_TYPE(''Horry st.'', ''Edinburgh'', ''EH12 2ER'', ''909'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07712365438'')))','0.003',9999,to_date('16-FEB-00','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1104,'saving',145,'SYSTEM.BRANCH_TYPE(''Marry st.'', ''Edinburgh'', ''EH1 4QH'', ''907'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07765781234'')))','0.013',444,to_date('02-MAR-00','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1105,'current',1444,'SYSTEM.BRANCH_TYPE(''Horry st.'', ''Edinburgh'', ''EH12 2ER'', ''909'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07712365438'')))','0.05',100,to_date('04-APR-00','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1106,'saving',800,'SYSTEM.BRANCH_TYPE(''Wenhua st.'', ''Beijing'', ''400000'', ''914'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''00861234567'')))','0.003',2208,to_date('28-FEB-10','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1107,'current',123,'SYSTEM.BRANCH_TYPE(''Tianan st.'', ''Edinburgh'', ''EH1 1RR'', ''915'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07741234281'')))','0.04',450,to_date('21-DEC-09','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1108,'saving',400,'SYSTEM.BRANCH_TYPE(''Bridge st.'', ''Glasglow'', ''G18 1QQ'', ''903'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''01413214556'')))','0.05',600,to_date('21-NOV-16','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1109,'current',7800,'SYSTEM.BRANCH_TYPE(''Chao Yang st.'', ''London'', ''E11 W1'', ''904'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07702346542'')))','0.03',null,to_date('01-JAN-00','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1110,'saving',1235,'SYSTEM.BRANCH_TYPE(''Chao Yang st.'', ''London'', ''E11 W1'', ''904'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07702346542'')))','0.01',10000,to_date('21-FEB-00','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1111,'saving',10000,'SYSTEM.BRANCH_TYPE(''Qinling St.'', ''Zhengzhou'', ''450001'', ''912'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''08618532109175'')))','0.09',500,to_date('16-JUN-09','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1112,'current',1220,'SYSTEM.BRANCH_TYPE(''Taobao'', ''Striling'', ''ST1 ER3'', ''919'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07341235781'')))','0.002',200,to_date('03-MAR-18','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1113,'saving',88000,'SYSTEM.BRANCH_TYPE(''Marry st.'', ''Edinburgh'', ''EH1 4QH'', ''907'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07765781234'')))','0.04',1000,to_date('15-JUL-19','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1114,'current',432,'SYSTEM.BRANCH_TYPE(''King st.'', ''Edinburgh'', ''EH3 5AR'', ''911'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''013198745612'')))','0.06',100,to_date('30-MAY-14','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1115,'current',3420000,'SYSTEM.BRANCH_TYPE(''Horry st.'', ''Edinburgh'', ''EH12 2ER'', ''909'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07712365438'')))','0.01',9000,to_date('15-AUG-99','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1116,'saving',9888,'SYSTEM.BRANCH_TYPE(''Chao Yang st.'', ''London'', ''E11 W1'', ''904'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07702346542'')))','0.08',700,to_date('30-JUN-03','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1117,'current',10000,'SYSTEM.BRANCH_TYPE(''Horry st.'', ''Edinburgh'', ''EH12 2ER'', ''909'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07712365438'')))','0.012',5000,to_date('14-FEB-10','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1118,'saving',5600,'SYSTEM.BRANCH_TYPE(''Tianan st.'', ''Edinburgh'', ''EH1 1RR'', ''915'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''07741234281'')))','0.014',5000,to_date('13-MAY-99','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1119,'current',9888,'SYSTEM.BRANCH_TYPE(''Wenhua st.'', ''Beijing'', ''400000'', ''914'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''00861234567'')))','0.009',8000,to_date('02-AUG-98','DD-MON-RR'));
Insert into SYSTEM.ACCOUNT (ACCOUNT_NUMBER,ACC_TYPE,BALANCE,BRANCH_ID,INTEREST_RATE,LIMIT_OF_FREE_OD,OPEN_DATE) values (1120,'saving',2000,'SYSTEM.BRANCH_TYPE(''Yahoo st.'', ''Oxford'', ''11ER 3BT'', ''917'', SYSTEM.PHONE_TYPE_TABLE(SYSTEM.PHONE_NESTED(''branch'', ''01312314231'')))','0.008',4000,to_date('17-JUN-07','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index ACCOUNTNUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ACCOUNTNUMBER" ON "SYSTEM"."ACCOUNT" ("ACCOUNT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007034
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007034" ON "SYSTEM"."ACCOUNT" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACCOUNT" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ACCOUNT" ADD CONSTRAINT "ACCOUNTNUMBER" PRIMARY KEY ("ACCOUNT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ACCOUNT" ADD CONSTRAINT "OPENDATE" CHECK (open_date IS NOT NULL) ENABLE;
  ALTER TABLE "SYSTEM"."ACCOUNT" ADD CONSTRAINT "BRANCH_ID" CHECK (branch_id IS NOT NULL) ENABLE;
  ALTER TABLE "SYSTEM"."ACCOUNT" ADD CONSTRAINT "ACCTYPE" CHECK (acc_type IS NOT NULL) ENABLE;
